== Design

Following is a diagram that illustrates `jq-front` 's processing pipeline design.

[ditaa, target="images/pipeline"]
.jq-front's pipeline
----
_Inheritance!
+--------------------------------------------------------------------------------------+
|                                                                                      |
|          file-level inheritance             local node materialization               |
|                 +----+                             +-----+                           |
|   +-------------+ {o}+-=----------+   +------------+ {o} +-=------------+            |
|   |             +----+            |   |            +-----+              | 0...n      |
|   V                               V   V                                 V            |
| +------+                         +-------+                         +------------+    |
| |Source|                         |Work(1)|                         |LocalNodes  |    |
| |{d}   |                         |{d}    |                         |{d}         |    |
| +------+                         +-------+                         +------------+    |
|                                      ^        node-level inheritance     ^           |
|                                      |              +-----+              |           |
|                                      +--------------+ {o} +--------------+           |
|                                                     +--+--+                          |
|                                                        |                             |
+--------------------------------------------------------|-----------------------------+
                                                         :
                                                         V
                                                     +---+---+
                                                     |Work(2)|
                                                     |{d}    |
                                                     +---+---+
                                                         ^
                                                         |
                                                         |
                                                      +--+--+
                                                      | {o} | templating(optional)
                                                      +--+--+
  +----+       +----+                                    |
  |A{o}+-=---->+B{o}| (A writes to B)                    :
  +----+       +----+                                    V
                                                     +---+---+
  +----+       +----+                                |Output |
  |A{o}+------>+B{o}| (A reads from B)               |{d}    |
  +----+       +----+                                +---+---+

----

As shown, it consists of four main components, which are "file-level inheritance", "local node materialization", "node-level inheritance", and "templating".

Designs of those components will be described in the rest of this section.

=== File-level Inheritance

'File-level Inheritance' composes a new JSON file from a given one by expanding the files provided through the top-level `$extends` attribute.

At the end of this process, the attribute is removed and copied to the output, "Work(1)" in the diagram.

=== Local node Materialization

If the file, "Work(1)" has `$local` attribute whose value is an object node, nodes associated with keys under the attribute are dumped under a temporary directory.
The temporary directory is called 'local node directory'.
The 'local node directory' and its contents are utilized by the "node-level inheritance' mechanism.

=== Node-level Inheritance

Node-level Inheritance mechanism is a bit more complicated than the file-level one.

1. Create a base JSON object by the following procedure.
a. Scan paths of all internal nodes.
b. For each path, if it ends with `"$extends"`, expand the files specified by the attribute.
c. Assign the JSON node created in step b. to the parent of the `$extends` attribute.
2. Overlay the JSON object created in the step. 1 with an original JSON object.
3. Remove nodes, i.e., `$extends` and `$local` nodes from the JSON object created in the step 2.

'Local node directory' is inserted before the first entry of `JF_PATH` environment variable when a file to be expanded is searched during the step 1. b.

=== Templating

Templating is executed by performing `eval` on every text node whose value starts with `template:` in a JSON object ```Work(2)```.
The order where it is applied is determined by ```jq```'s ```path(..)``` function.
Note that it is not defined in `jq` 's manual<<jq>> how keys are sorted within an object node although they seem to be sorted by dictionary order.

----
echo {CONTENT OF Work(2)}
----

And this causes expansions of bash expressions inside the content of "Work(2)" and that expanded string will be printed by the `echo` command.


